/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_DEV_RPC_SKALESTATSFACE_H_
#define JSONRPC_CPP_STUB_DEV_RPC_SKALESTATSFACE_H_

#include "ModularServer.h"

namespace dev {
namespace rpc {

class SkaleStatsFace : public ServerInterface< SkaleStatsFace > {
public:
    SkaleStatsFace() {
        this->bindAndAddMethod( jsonrpc::Procedure( "skale_stats", jsonrpc::PARAMS_BY_POSITION,
                                    jsonrpc::JSON_STRING, NULL ),
            &dev::rpc::SkaleStatsFace::skale_statsI );
        this->bindAndAddMethod( jsonrpc::Procedure( "skale_nodesRpcInfo",
                                    jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL ),
            &dev::rpc::SkaleStatsFace::skale_nodesRpcInfoI );
        this->bindAndAddMethod( jsonrpc::Procedure( "skale_imaInfo", jsonrpc::PARAMS_BY_POSITION,
                                    jsonrpc::JSON_STRING, NULL ),
            &dev::rpc::SkaleStatsFace::skale_imaInfoI );

        this->bindAndAddMethod( jsonrpc::Procedure( "skale_browseEntireNetwork",
                                    jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL ),
            &dev::rpc::SkaleStatsFace::skale_browseEntireNetworkI );
        this->bindAndAddMethod( jsonrpc::Procedure( "skale_cachedEntireNetwork",
                                    jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, NULL ),
            &dev::rpc::SkaleStatsFace::skale_cachedEntireNetworkI );
    }

    inline virtual void skale_statsI( const Json::Value& request, Json::Value& response ) {
        ( void ) request;
        response = this->skale_stats();
    }
    inline virtual void skale_nodesRpcInfoI( const Json::Value& request, Json::Value& response ) {
        ( void ) request;
        response = this->skale_nodesRpcInfo();
    }
    inline virtual void skale_imaInfoI( const Json::Value& request, Json::Value& response ) {
        ( void ) request;
        response = this->skale_imaInfo();
    }

    inline virtual void skale_browseEntireNetworkI(
        const Json::Value& request, Json::Value& response ) {
        response = this->skale_browseEntireNetwork( request );
    }
    inline virtual void skale_cachedEntireNetworkI(
        const Json::Value& request, Json::Value& response ) {
        response = this->skale_cachedEntireNetwork( request );
    }


    virtual Json::Value skale_stats() = 0;
    virtual Json::Value skale_nodesRpcInfo() = 0;
    virtual Json::Value skale_imaInfo() = 0;

    virtual Json::Value skale_browseEntireNetwork( const Json::Value& request ) = 0;
    virtual Json::Value skale_cachedEntireNetwork( const Json::Value& request ) = 0;
};  /// class SkaleStatsFace

}  // namespace rpc
}  // namespace dev

#endif  // JSONRPC_CPP_STUB_DEV_RPC_SKALESTATSFACE_H_
