name: Custom Docker and Binary

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        default: ''
        required: true
      image_version:
        description: 'Image version for docker hub'
        default: ''
        required: true
      cmake_options:
        description: 'Additional cmake options'
        default: ''
        required: false
      cmake_build_type:
        description: 'CMake build type'
        type: choice
        required: true
        options: 
          - Debug
          - RelWithDebInfo
          - Release
        default: RelWithDebInfo
      node_type:
        description: 'Node type'
        type: choice
        options: 
          - core
          - core+historic
          - historic
        required: false
        default: core
      protocol_profile:
        description: 'Protocol profile'
        type: choice
        options: 
          - core
          - bite
          - fair
        required: false
        default: core

jobs:
  core_build:
    if: github.event.inputs.node_type != 'historic'
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      image_version: ${{ github.event.inputs.image_version }}
      branch_name: ${{ github.event.inputs.branch_name }}
      cmake_options: ${{ github.event.inputs.cmake_options }}
      cmake_build_type: ${{ github.event.inputs.cmake_build_type }}
      protocol_profile: ${{ github.event.inputs.protocol_profile }}
      node_type: core
      version_suffix_mode: cmake_build_type_protocol_profile_and_node_type
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  historic_build:
    if: github.event.inputs.node_type != 'core'
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      image_version: ${{ github.event.inputs.image_version }}
      branch_name: ${{ github.event.inputs.branch_name }}
      cmake_options: ${{ github.event.inputs.cmake_options }}
      cmake_build_type: ${{ github.event.inputs.cmake_build_type }}
      protocol_profile: ${{ github.event.inputs.protocol_profile }}
      node_type: historic
      version_suffix_mode: cmake_build_type_protocol_profile_and_node_type
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
