name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - 'v*.*.*'
      - master
      - develop
      - beta
      - stable

  
jobs:
  configure:
    if: github.event.pull_request.merged == true
    name: Configure release
    runs-on: ubuntu-latest
    outputs:
      version_orig: ${{ steps.set-version.outputs.version_orig }}
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Read and calculate version
        id: set-version
        run: |
          VERSION=$(cat VERSION)
          VERSION=$(bash ./scripts/calculate_version.sh $BRANCH_NAME $VERSION)
          echo "Calculated version: $VERSION"

          ( test "$BRANCH_NAME" = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV

          echo "::set-output name=version_orig::$VERSION"
          
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-version.outputs.version_orig }}
          release_name: ${{ steps.set-version.outputs.version_orig }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}

  build:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: core
      node_type: core
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit

  build-historic:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: core
      node_type: historic
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit
  
  build-fair:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: fair
      node_type: core
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit
  
  build-fair-historic:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: fair
      node_type: historic
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit
  
  build-bite:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: bite
      node_type: core
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit
  
  build-bite-historic:
    needs: configure
    uses: ./.github/workflows/setup-build-publish.yml
    with:
      branch_name: ${{ github.ref_name }}
      image_version: ${{ needs.configure.outputs.version_orig }}
      cmake_build_type: "RelWithDebInfo"
      protocol_profile: bite
      node_type: historic
      release_url: ${{ needs.configure.outputs.release_url }}
      version_suffix_mode: protocol_profile_and_node_type
    secrets: inherit
  
  functional-tests:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for orig build
    needs: build
    with:
      version: ${{ needs.build.outputs.version }}
    secrets: inherit

  functional-tests-historic:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for historic build
    needs: build-historic
    with:
      version: ${{ needs.build-historic.outputs.version }}
    secrets: inherit
  
  functional-tests-fair:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for fair build
    needs: build-fair
    with:
      version: ${{ needs.build-fair.outputs.version }}
    secrets: inherit
  
  functional-tests-fair-historic:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for fair-historic build
    needs: build-fair-historic
    with:
      version: ${{ needs.build-fair-historic.outputs.version }}
    secrets: inherit
  
  functional-tests-bite:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for bite build
    needs: build-bite
    with:
      version: ${{ needs.build-bite.outputs.version }}
    secrets: inherit
  
  functional-tests-bite-historic:
    uses: ./.github/workflows/functional-tests.yml
    name: Functional testing for bite-historic build
    needs: build-bite-historic
    with:
      version: ${{ needs.build-bite-historic.outputs.version }}
    secrets: inherit 
