name: 'Setup, Build and Publish'
on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        description: 'Branch name'
        required: true
      image_version:
        type: string
        description: 'Image version for docker hub'
        required: true
      cmake_options:
        type: string
        description: 'Additional cmake options'
        required: false
      build_type:
        type: string
        description: 'Build type of skaled binary'
        required: true
      node_type:
        type: string
        description: 'Node type of skaled build'
        required: true
      release_url:
        type: string
        description: 'URL of the GitHub release associated with this build (if applicable)'
        required: false
      use_plain_version:
        type: boolean
        description: 'Use only the image version without appending the build type suffix'
        default: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    outputs:
      version:
        description: "The image version published to DockerHub"
        value: ${{ jobs.main.outputs.version }}
      
jobs:
  main:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ env.VERSION }}
    env: 
      CC: gcc-11
      CXX: g++-11
      BRANCH: ${{ inputs.branch_name }}
      BUILD_TYPE: ${{ inputs.build_type }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PLAIN_VERSION: ${{ inputs.use_plain_version }}
    steps:
      - name: Prepare workflow variables
        if: inputs.node_type == 'core'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (historic)
        if: inputs.node_type == 'historic'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX-historic
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DHISTORIC_STATE=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (BITE)
        if: inputs.node_type == 'bite'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DBITE=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (BITE-HISTORIC)
        if: inputs.node_type == 'bite-historic'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DBITE=1 -DHISTORIC_STATE=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (FAIR)
        if: inputs.node_type == 'fair'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DFAIR=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (FAIR-HISTORIC)
        if: inputs.node_type == 'fair-historic'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DFAIR=1 -DHISTORIC_STATE=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (BITE2)
        if: inputs.node_type == 'bite2'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DBITE2=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - name: Prepare workflow variables (BITE2-HISTORIC)
        if: inputs.node_type == 'bite2-historic'
        run: |
          export VERSION_SUFFIX=$(echo "$BUILD_TYPE" | tr '[:upper:]' '[:lower:]')
          [[ $PLAIN_VERSION = "true" ]] && export VERSION=${{ inputs.image_version }} || \
            export VERSION=${{ inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export CMAKE_OPTS="-DBITE2=1 -DHISTORIC_STATE=1 ${{ inputs.cmake_options }}"
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch_name }}
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev autoconf build-essential cmake libprocps-dev libtool texinfo wget yasm flex bison btrfs-progs python3 python3-pip gawk git vim doxygen
          sudo apt-get install -y make pkg-config libgnutls28-dev libssl-dev unzip zlib1g-dev libgcrypt20-dev gcc-11 g++-11 gperf clang-format-11 gnutls-dev
          sudo apt-get install -y nettle-dev libhiredis-dev redis-server google-perftools libgoogle-perftools-dev lcov libv8-dev 
          sudo apt-get install -y gettext

          # Remove deps installed in the next steps
          sudo apt-get purge -y libbz2-dev liblz4-dev

      - name: Build dependencies
        run: |
          [[ $BUILD_TYPE = "Debug" ]] && export DEBUG_FLAG=1 || export DEBUG_FLAG=0
          cd deps
          ./build.sh PARALLEL_COUNT=$(nproc) DEBUG=$DEBUG_FLAG
          cd ..

      - name: Build skaled binary
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build
          cmake_build_type: ${{ env.BUILD_TYPE }}
          cmake_args: ${{ env.CMAKE_OPTS }}
          make_target: skaled
          
      - name: Binary post-processing
        run: |
          cd build
          if [[ "$BUILD_TYPE" = "Release" ]]; then
              debug_wc=$(objdump -h skaled/skaled | grep -i debug | wc -l)
              sym_wc=$(readelf -s skaled/skaled | wc -l)
              if (( debug_wc != 0 || sym_wc > 10000 )); then
                  exit 1
              fi
          fi
          if [[ "$BUILD_TYPE" = "RelWithDebInfo" ]]; then
              cp skaled/skaled skaled/skaled-debug
              strip --strip-all skaled/skaled
          fi
          cd ..

      - name: Build and publish docker image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cp build/skaled/skaled scripts/skale_build/executable/
          bash ./scripts/build_and_publish.sh
  
      - name: Upload skaled binary as artifact
        uses: actions/upload-artifact@v4
        if: inputs.release_url == ''
        with:
          name: skaled-${{ inputs.node_type }}
          path: ./build/skaled/skaled

      - name: Upload skaled binary to Release
        if: inputs.release_url != ''
        uses: actions/upload-release-asset@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./build/skaled/skaled
          asset_name: skaled-${{ inputs.node_type }}
          asset_content_type: application/octet-stream

      - name: Upload debug binary to Release
        if: inputs.release_url != '' && inputs.build_type == 'RelWithDebInfo'
        uses: actions/upload-release-asset@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./build/skaled/skaled-debug
          asset_name: skaled-debug-${{ inputs.node_type }}
          asset_content_type: application/octet-stream
