name: 'Setup, Build and Publish'
on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        description: 'Branch name'
        required: true
      image_version:
        type: string
        description: 'Image version for docker hub'
        required: true
      cmake_options:
        type: string
        description: 'Additional cmake options'
        required: false
      cmake_build_type:
        type: string
        description: 'CMake build type of skaled binary: Debug, RelWithDebInfo, or Release'
        required: true
      protocol_profile:
        type: string
        description: 'Protocol profile of skaled build: core, bite, or fair'
        required: true
      node_type:
        type: string
        description: 'Node type of skaled build: core or historic'
        required: true
      release_url:
        type: string
        description: 'URL of the GitHub release associated with this build (if applicable)'
        required: false
      version_suffix_mode:
        type: string
        description: 'Docker image version suffix mode: none, protocol_node, or cmake_protocol_node'
        default: cmake_protocol_node
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    outputs:
      version:
        description: "The image version published to DockerHub"
        value: ${{ jobs.main.outputs.version }}
      
jobs:
  main:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ env.VERSION }}
    env: 
      CC: gcc-11
      CXX: g++-11
      BRANCH: ${{ inputs.branch_name }}
      CMAKE_BUILD_TYPE: ${{ inputs.cmake_build_type }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      VERSION_SUFFIX_MODE: ${{ inputs.version_suffix_mode }}
    steps:
      - name: Prepare image version
        run: |
          if [[ "$CMAKE_BUILD_TYPE" = "Release" ]]; then
            export CMAKE_BUILD_TYPE_SUFFIX=""
          else
            export CMAKE_BUILD_TYPE_SUFFIX="-$(echo "$CMAKE_BUILD_TYPE" | tr '[:upper:]' '[:lower:]')"
          fi

          case "${{ inputs.protocol_profile }}" in
            core)
              export PROTOCOL_PROFILE_SUFFIX=""
              export BUILD_PROFILE="core"
              ;;
            bite)
              export PROTOCOL_PROFILE_SUFFIX="-bite"
              export BUILD_PROFILE="bite"
              ;;
            fair)
              export PROTOCOL_PROFILE_SUFFIX="-fair"
              export BUILD_PROFILE="fair"
              ;;
            *)
              echo "Unsupported protocol_profile: ${{ inputs.protocol_profile }}"
              exit 1
              ;;
          esac

          case "${{ inputs.node_type }}" in
            core)
              export NODE_TYPE_SUFFIX=""
              ;;
            historic)
              export NODE_TYPE_SUFFIX="-historic"
              [[ "$BUILD_PROFILE" = "core" ]] && export BUILD_PROFILE="historic" || export BUILD_PROFILE="$BUILD_PROFILE-historic"
              ;;
            *)
              echo "Unsupported node_type: ${{ inputs.node_type }}"
              exit 1
              ;;
          esac

          if [[ "$VERSION_SUFFIX_MODE" = "none" ]]; then
            export VERSION=${{ inputs.image_version }}
          elif [[ "$VERSION_SUFFIX_MODE" = "protocol_node" ]]; then
            export VERSION=${{ inputs.image_version }}$PROTOCOL_PROFILE_SUFFIX$NODE_TYPE_SUFFIX
          elif [[ "$VERSION_SUFFIX_MODE" = "cmake_protocol_node" ]]; then
            export VERSION=${{ inputs.image_version }}$CMAKE_BUILD_TYPE_SUFFIX$PROTOCOL_PROFILE_SUFFIX$NODE_TYPE_SUFFIX
          else
            echo "Unsupported version_suffix_mode: $VERSION_SUFFIX_MODE"
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_PROFILE=$BUILD_PROFILE" >> $GITHUB_ENV

      - name: Prepare workflow variables
        run: |
          export CMAKE_OPTS="${{ inputs.cmake_options }}"
          if [[ "${{ inputs.protocol_profile }}" = "bite" ]]; then
            export CMAKE_OPTS="-DBITE=1 $CMAKE_OPTS"
          fi
          if [[ "${{ inputs.protocol_profile }}" = "fair" ]]; then
            export CMAKE_OPTS="-DFAIR=1 $CMAKE_OPTS"
          fi
          if [[ "${{ inputs.node_type }}" = "historic" ]]; then
            export CMAKE_OPTS="-DHISTORIC_STATE=1 $CMAKE_OPTS"
          fi
          echo "CMAKE_OPTS=$CMAKE_OPTS" >> $GITHUB_ENV
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch_name }}
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev autoconf build-essential cmake libprocps-dev libtool texinfo wget yasm flex bison btrfs-progs python3 python3-pip gawk git vim doxygen
          sudo apt-get install -y make pkg-config libgnutls28-dev libssl-dev unzip zlib1g-dev libgcrypt20-dev gcc-11 g++-11 gperf clang-format-11 gnutls-dev
          sudo apt-get install -y nettle-dev libhiredis-dev redis-server google-perftools libgoogle-perftools-dev lcov libv8-dev 
          sudo apt-get install -y gettext

          # Remove deps installed in the next steps
          sudo apt-get purge -y libbz2-dev liblz4-dev

      - name: Build dependencies
        run: |
          [[ $CMAKE_BUILD_TYPE = "Debug" ]] && export DEBUG_FLAG=1 || export DEBUG_FLAG=0
          cd deps
          ./build.sh PARALLEL_COUNT=$(nproc) DEBUG=$DEBUG_FLAG
          cd ..

      - name: Build skaled binary
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          cmake_args: ${{ env.CMAKE_OPTS }}
          make_target: skaled
          
      - name: Binary post-processing
        run: |
          cd build
          if [[ "$CMAKE_BUILD_TYPE" = "Release" ]]; then
              debug_wc=$(objdump -h skaled/skaled | grep -i debug | wc -l)
              sym_wc=$(readelf -s skaled/skaled | wc -l)
              if (( debug_wc != 0 || sym_wc > 10000 )); then
                  exit 1
              fi
          fi
          if [[ "$CMAKE_BUILD_TYPE" = "RelWithDebInfo" ]]; then
              cp skaled/skaled skaled/skaled-debug
              strip --strip-all skaled/skaled
          fi
          cd ..

      - name: Build and publish docker image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cp build/skaled/skaled scripts/skale_build/executable/
          bash ./scripts/build_and_publish.sh
  
      - name: Upload skaled binary as artifact
        uses: actions/upload-artifact@v4
        if: inputs.release_url == ''
        with:
          name: skaled-${{ env.BUILD_PROFILE }}
          path: ./build/skaled/skaled

      - name: Upload skaled binary to Release
        if: inputs.release_url != ''
        uses: actions/upload-release-asset@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./build/skaled/skaled
          asset_name: skaled-${{ env.BUILD_PROFILE }}
          asset_content_type: application/octet-stream

      - name: Upload debug binary to Release
        if: inputs.release_url != '' && inputs.cmake_build_type == 'RelWithDebInfo'
        uses: actions/upload-release-asset@latest
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./build/skaled/skaled-debug
          asset_name: skaled-debug-${{ env.BUILD_PROFILE }}
          asset_content_type: application/octet-stream
